Hands
FSA-Deckr/deckr pull request #17
Opened 2020-12-08 04:11 UTC by cwyoder

Users can add cards to their hand by dragging to the bottom of the table.

gameState should adjust along with changes, so cards in other users hands will exist in the table upon a user joining, but they cannon be seen.

2020-12-08 16:55 UTC, adam-adair commented on server/index.js
> +// app.use(morgan('dev'));
I think we want to keep the logs on dev

2020-12-08 16:55 UTC, adam-adair commented on server/socketServer.js
> +        socket.on('addCardToHand', function(cardState) {
you could destructure this if you wanna

2020-12-08 16:57 UTC, adam-adair commented on src/Card.js
> +        this.addToHand = dragX > canvasWidth - 100;
maybe should have 100 in constants so we can change dimensions if we change table size

2020-12-08 16:59 UTC, adam-adair commented on src/DeckrTable.js
> +        // socket.emit('sendChip', { chip: chipA, room: gameState.room, otherPlayerDragging: false })
I don't have strong feelings about this and I'm sure I've broken the rules myself, but in prior code reviews, Eliot seemed to think leaving commented out code was bad form.

2020-12-08 17:13 UTC, adam-adair commented on src/views/table.js
> +        <p>
Is this used anywhere? I assume we want to show the number of cards in players hands. I didn't find it, but maybe I missed somethig.

2020-12-08 17:15 UTC, adam-adair requested changes
Left a comment to this effect, but I couldn't get hands to show between players

I found a few bugs testing this:
When I have a card in hand as P2, and I deal a card as P1, my P2 card in hand rotates.
I'm not 100% sure how to recreate this, but when I take a card out of my hand as a player and then try to move it as another player, the world bounds aren't quite right. I'm able to take it off the screen sometimes.

2020-12-09 19:26 UTC, cwyoder commented
I think I fixed all of the errors/bugs, except for one with stacks ... cards in hand do not change their depth order when moving them in your hand, which makes it harder to reorganize them in your hand. Also, the stack button covers up the card number while it's in your hand.

My opinion on this is that cards in hand should not be able to be stacked, so that stack button shouldn't show up in there at all. I'm free all day today to pair on this.

2020-12-10 02:33 UTC, adam-adair approved these changes
Looks good.

2020-12-10 02:33 UTC, merged